### ISSUE TITLE
E484: Can't open file /var/folders/

### ISSUE THREAD

**Issue by iurnah** [instant-markdown/vim-instant-markdown#101]
I followed the install instruction in OSX 10.11.6, with macvim and termianl vim, both got the following error. Could anyone help to figure out what wrong?

Error detected while processing function <SNR>83_previewMarkdown[1]..<SNR>83_startDaemon[1]..<SNR>83_system:
line    4:
E484: Can't open file /var/folders/pv/7cps_m251374nmxz32j8kc7r000xwj/T/vpmmd1s/9

**Comment by trisys3** [comment]
I got something similar with Ubuntu 16.04 & vim 8:

Error detected while processing function <SNR>116_previewMarkdown[1]..<SNR>116_st
artDaemon[12]..<SNR>116_systemasync[5]..<SNR>116_system:
line    4:
E484: Can't open file /tmp/vDFn3hw/5

In case this is relevant, I installed `vim` from (GitHub) source, as the default Ubuntu version is 7.4.
