### ISSUE TITLE
windows not work

### ISSUE THREAD

**Issue by axiaoxin** [instant-markdown/vim-instant-markdown#108]
system: win7-64 gvim/cmder's vim
installed: node\npm curl
it dose not like macosx/linux work fine, no browser is open to preview the md

**Comment by 2eleven2** [comment]
Same problem as you.
win10-64 gvim.
I installed node.js/npm, and then `npm -g install instant-markdown-d`. I al so installed curl and it can be called through cmd. However, when I open markdown files, nothing happened.

**Comment by suan** [comment]
Hi, the windows support is in master but not yet released. You will have to specify the repo and master branch when installing instant-markdown-d through npm

**Comment by woshichuanqilz** [comment]
@suan I use `npm -g install https://github.com/suan/instant-markdown-d.git#master` to install. And the broswer won't start either, and the localhost:8090 show noting.
![0113083156.png](http://7xpvdr.com1.z0.glb.clouddn.com/0113083156.png)

**Comment by giseray** [comment]
It didn't work for me at the first time. Then I found if I installed the vim script using my vim-plug system, it worked. So it seems that the location of the script needs to be changed if you are using some plugin managing plugin. In my case, the path should be ```~\.vim\plugged\vim-instant-markdown\after\ftplugin\markdown\instant-markdown.vim```.

**Comment by jiftle** [comment]
me too, I do that like (http://www.jianshu.com/p/24aefcd4ca93). but it is not work. os is win7 x64,vim is 8.0.
