### ISSUE TITLE
writing new lines breaks rendering

### ISSUE THREAD

**Issue by t-0-m-1-3** [instant-markdown/vim-instant-markdown#141]
Editing a markdown file will open the rendered browser, but editing that file breaks the syntax in the webpage and the markdown no longer renders correctly. 
![image](https://user-images.githubusercontent.com/20537914/54383860-0586c080-4661-11e9-8940-e95a9bf01b23.png)

Switching files works to render the new file, but I have to consistently switch/close between markdown files to get the one I'm working on to reload.

**Comment by ashwinvis** [comment]
What version of vim/neovim are you using?

**Comment by t-0-m-1-3** [comment]
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 06 2019 03:41:10)
Included patches: 1-875, 878, 884, 948
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
```

**Comment by ashwinvis** [comment]
That looks ok. Are you using the latest version? The one on npm is outdated. To get the most recent version install as follows:

    npm -g install https://github.com/suan/instant-markdown-d.git#master

Also try setting:

    let g:instant_markdown_slow = 1

and see if it helps
