### ISSUE TITLE
jpg picture  can not display

### ISSUE THREAD

**Issue by Luffy4321** [instant-markdown/vim-instant-markdown#143]
the jpg picture can  not work well suddenly for some days.  I try Typora at the same time, it cannot work ,too. but yesterday,I update the Typora ,the problem is fixed, how about  this one?
thanks advances !
OS:MacOS Mojave 10.14.3

**Comment by Luffy4321** [comment]
@suan

**Comment by ashwinvis** [comment]
Did you try: `let g:instant_markdown_open_to_the_world = 1`

**Comment by ashwinvis** [comment]
Should be fixed in suan/instant-markdown-d#60
