### ISSUE TITLE
Fail to see math symbol in preview

### ISSUE THREAD

**Issue by yushangakki** [instant-markdown/vim-instant-markdown#170]
# Problem summary: fail to see math symbol in preview

## Environment Information

 * OS: Macos 10.14.4
 * Vim / Neovim version:VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2019 22:54:00)
macOS version
Included patches: 1-1722
Compiled by Homebrew
 * Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

## Provide the debug output (required)

Run `cat my_markdown_file.md | instant-markdown-d --mathjax --debug` and paste the
console output here:

```sh
(node:98365) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
connection established!
```

## Steps to reproduce the issue (required)

Start with command you used to install `instant-markdown-d`

 1.sudo npm -g install instant-markdown-d
 2.instant-markdown-d --mathjax
 3.

**Comment by ashwinvis** [comment]
Can you generate a log file:

```vim
let g:instant_markdown_logfile = '/tmp/instant_markdown.log'
```

**Comment by ashwinvis** [comment]
It muse be because the old version of instant-markdown-d was used.
