### ISSUE TITLE
Does not work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by pmatulis** [instant-markdown/vim-instant-markdown#174]
Followed the install steps, used the defaults in ~/.vimrc, opened a README.md file, invoked :InstantMarkdownPreview. There is nothing listening on port 8888.

**Comment by ashwinvis** [comment]
Could you generate some debug logs as directed in the issue template? https://github.com/suan/vim-instant-markdown/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by plenaerts** [comment]
I had to manually install curl on ubuntu.

**Comment by ashwinvis** [comment]
Of course, the dependencies are mentioned in the README :+1:. Is this comment (by @plenaerts) related to the original report (by @pmatulis)?

**Comment by plenaerts** [comment]
Yes, it relates to the original report.

If @pmatulis didn't read down to the requirements and has followed only the quick install instructions, then he'll clearly see an error for curl missing on stock ubuntu in the debug log.

 @pmatulis should post the contents of the debug log as requested.
