### ISSUE TITLE
content security policy - scripts are blocked

### ISSUE THREAD

**Issue by barun108** [instant-markdown/vim-instant-markdown#179]
When I run instant markdown 
I get blank page
in console i get this error

Content Security Policy: The page’s settings blocked the loading of a resource at https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/woff/MathJax_Size3-Regular.woff (“default-src”).

**Comment by ashwinvis** [comment]
> g:instant_markdown_allow_unsafe_content
> 
> By default, scripts are blocked. To allow scripts to run, edit your .vimrc and add
> 
`let g:instant_markdown_allow_unsafe_content = 1`
