### ISSUE TITLE
always get EOF in browser.

### ISSUE THREAD

**Issue by iysheng** [instant-markdown/vim-instant-markdown#183]
# Problem summary
I always get EOF in firefox browser when I do InstantMarkdownPreview.
## Expected
get markdown preview correct

## Environment Information

 * OS:Fedora 33
 * Vim / Neovim version:vim 8.2 build by local
 * Browser:firefox 81.0.1(64 bit)

## Provide the debug output (required)

Run `cat my_markdown_file.md | instant-markdown-d --mathjax --debug` and paste the
console output here:

```sh
instant-mardown-d version: v0.2.0-rc.2
nodejs version: v14.13.0
Run the following to manually open browser:
    xdg-open http://localhost:8090/
Rendered html saved as debug.html
```
stock with upper print,
## Generate log files (required)
when I cat the file **/tmp/instant_markdown.log**, i get nothing, the file just **1B** size.
```
let g:instant_markdown_logfile = '/tmp/instant_markdown.log'
```

 1. Add the above in your `~/.vimrc` or `~/.config/nvim/init.vim`. Modify the
    path if needed and generate the log file.
 1. Minimal `~/.vimrc` or `~/.config/nvim/init.vim` where variables for
    `vim-instant-markdown` defined
 1. `debug.html`

## Steps to reproduce the issue (required)

Start with command you used to install `instant-markdown-d`

 1.
``` bash
 npm config set registry https://registry.npm.taobao.org --global
 npm config set disturl https://npm.taobao.org/dist --global
```
 2.
``` bash
sudo npm -g install instant-markdown-d
```
 3.

## Screen shot (if possible)
[![0Nd0k8.png](https://s1.ax1x.com/2020/10/06/0Nd0k8.png)](https://imgchr.com/i/0Nd0k8)

**Comment by ashwinvis** [comment]
Thank you for the detailed report. Have you installed `curl`?

**Comment by iysheng** [comment]
> Thank you for the detailed report. Have you installed `curl`?

yeah, and nowadays it's just ok. So just close this issue now.
