### ISSUE TITLE
Lack of smdv using‘s explanation

### ISSUE THREAD

**Issue by Yeyuehuke** [instant-markdown/vim-instant-markdown#191]
I'm using smdv for this plug, and here I found that something should be noticed:

1. the plug config option let g:instant_markdown_python appear in your doc, but you didn't explain it.
2. when using smdv I found that my browser can open the file content, but can't read .md file. Then I go to https://github.com/flaport/smdv and it said that the user need to install pandoc, then smdv would run correctly. I guess the other requirements will be installed automaticly by pip, but the pandoc is independent of others so we need to install it manually.

if there's anybody using smdv in this plug meet some trouble, this could be working.

Like your plug! Have a nice day!

**Comment by ashwinvis** [comment]
Thanks for raising the issue, but I think it is up to `smdv` to raise a helpful error message. Can that be done @flaport?
