### ISSUE TITLE
[Feature Request] Blocklist certain paths/patterns

### ISSUE THREAD

**Issue by erikw** [instant-markdown/vim-instant-markdown#198]
Hey,

first thanks for a great plugin. I've been using it for a long time!

One addition that I see would be beneficial would be to have the ability to configure certain paths or name patterns for which matching Markdown files are not previewed by this plugin.

For me, the base case is that I do want to preview a Markdown file I open up in vim. That said, there are also certain cases e.g. when I work in `~/src/someproject` where I know that I actually never want the preview. In that case adding `~/src/someproject` to a blocklist would solve the problem.

Is this maybe already possible to configure but that I just missed it in the documentation? :)

**Comment by ashwinvis** [comment]
If someone knows more about Vim autocmds, feel free to comment.
