### ISSUE TITLE
Document support for vim8 build-in package manager users

### ISSUE THREAD

**Issue by SteveLauC** [instant-markdown/vim-instant-markdown#200]
Hey guys, nice work! 
This is **not** a problem report so I skip your issue template problems.

Vim8 introduced its own package manager, so I am wondering can we add the installation instruments for those build-in package manager users in *README.md* ?

Here is the approach to install *vim-install-markdown* using vim8 build-in package manager:
```shell
# NOTE: 
# 1. Please check you have git installed.
# 2. Please replace * with a package name you want.
git clone https://github.com/instant-markdown/vim-instant-markdown.git ~/.vim/pack/*/start/
```

**Comment by ashwinvis** [comment]
Pull requests welcome @SteveLauC !
