### ISSUE TITLE
How to invoke mathjax?

### ISSUE THREAD

**Issue by flossgeek** [instant-markdown/vim-instant-markdown#205]
I have `let g:instant_markdown_mathjax = 1` set in my .vimrc file. However, I can't manage to trigger mathjax formatting. Both `\(...\)` and `$$...$$` are without any result. How do I tackle this?

**Comment by ashwinvis** [comment]
Can you follow https://github.com/instant-markdown/vim-instant-markdown/blob/master/.github/ISSUE_TEMPLATE.md to understand your problem better?

**Comment by flossgeek** [comment]
Well, I think I found the problem already. I was first using the smdv python server, which had some quirks. Now I'm using the npm package of instant-markdown-d, which works much better and math is also displayed correctly.
Any clue on why smdv doesn't work? Is it not as well supported as instant-markdown-d?

**Comment by ashwinvis** [comment]
smdv relies on pandoc. You can check if it is available in your machine.

**Comment by flossgeek** [comment]
Yes, exactly. Pandoc is installed on my machine (by the package manager), but formulas aren't rendered as with the instant-markdown-d server.

**Comment by ashwinvis** [comment]
Strange. Perhaps smdv's pandoc call is missing some flags. I would recommend sorting this out at smdv's issue tracker.
