### ISSUE TITLE
Include in Neovims `plugins-setup.lua` to use it with Packer package manager

### ISSUE THREAD

**Issue by MannyFay** [instant-markdown/vim-instant-markdown#208]
Many Vim-Plug plugins work in Neovim to, if I do `use('a/plugin')`.  
It is possible to do the same with the vim-instant-markdown plugin?  
If yes, how I have to modify `Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown', 'do': 'yarn install'}` to use it in the lua file?

**Comment by ashwinvis** [comment]
Like

     use { 'instant-markdown/vim-instant-markdown', run='yarn install'}


Read the docs https://github.com/wbthomason/packer.nvim#specifying-plugins

**Comment by MannyFay** [comment]
Thank's for your help!  It works perfect!
...and thank you for this awesome plugin!!
If you going to plan a dark mode for your plugin, maybe I can help you in future?!

**Comment by ashwinvis** [comment]
There is a PR #207  and I made some minor requests. Unfortunatley the contributor is not responding. Can you do the finishing touches?
