### ISSUE TITLE
Render error while typing

### ISSUE THREAD

**Issue by GopherJ** [instant-markdown/vim-instant-markdown#209]
# Problem summary

If I use :InstantMarkdownPreview it's ok but if I just type the preview page will be incorrect while writing mathjax or mermaid

## Environment Information

 * OS:
 * Vim / Neovim version:
 * Browser:

## Steps to reproduce the issue (required)

Start with command you used to install `instant-markdown-d`. Use [a
minimal.vimrc](https://raw.githubusercontent.com/instant-markdown/vim-instant-markdown/master/doc/minimal.vimrc)
to reproduce the issue and open your markdown file as:

```sh
vim -u minimal.vimrc my_markdown_file.md
```

 1.
 2.
 3.

## Provide the debug output (required)

Run `cat my_markdown_file.md | instant-markdown-d --mathjax --debug`. It
generates a `debug.html` file - attach it here. Also, paste the console output
here:

```sh

```

**Comment by ashwinvis** [comment]
It should be more or less fixed by #204. Let me know if persists.
