### ISSUE TITLE
cant configure proper options for    g:instant_markdown_browser 

### ISSUE THREAD

**Issue by BartOrloy** [instant-markdown/vim-instant-markdown#210]
# Problem summary
i want use    

let g:instant_markdown_browser = "vivaldi --app="

## Expected
open vivaldi --app=<url>

## Environment Information
linux
vim 9

## Steps to reproduce the issue (required)

set 
let g:instant_markdown_browser = "vivaldi --app="

**Comment by ashwinvis** [comment]
What does the ` --app=` option do and why is it blank?

**Comment by BartOrloy** [comment]
> What does the ` --app=` option do and why is it blank?

hi, it is what we talk about :))) --app= launch  vivaldi app mode  and there should be localhost url from [vim-instant-markdown](https://github.com/instant-markdown/vim-instant-markdown) plugin...

**Comment by ashwinvis** [comment]
Then you should do something like `vivaldi --app=localhost:8888`.

**Comment by BartOrloy** [comment]
forget it... sure i can also launch it manually or use different plugin you are right... bye

**Comment by BartOrloy** [comment]
megalol

**Comment by ashwinvis** [comment]
Ok. Fine.

**Comment by ashwinvis** [comment]
For those wondering how to do it, both browser and its options should be configured in the vimrc

```vim
let g:instant_markdown_browser = "firefox --kiosk localhost:8888"
```

Or equivalent for the browser of your choice.
