### ISSUE TITLE
Provide Plantuml Support

### ISSUE THREAD

**Issue by CanNuhlar** [instant-markdown/vim-instant-markdown#211]
# Problem summary
Plantuml is not supported

## Expected
Plantumls are rendered into PNG

## Environment Information

 * OS: Debian 12
 * Vim / Neovim version: 9.0
 * Browser: Mozilla Firefox 102.14.0

## Steps to reproduce the issue (required)
1) Have an uml in your Markdown file such as;
```plantuml
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
```

-----

As a generic comment: I believe it might be the best that just calling an external tool for plantuml rendering to have this feature

**Comment by ashwinvis** [comment]
@CanNuhlar We already support mermaidjs. Would that suffice?

**Comment by CanNuhlar** [comment]
Well, functionally yes though I have a huge repo of umls that I want to keep visible on GitLab.

**Comment by ashwinvis** [comment]
I may not have time to implement it myself, but pull requests are welcome! All one needs to do is find a suitable markdown-it plugin for plantuml, search for "mermaid" in here and in instant-markdown-d and do the slmilar.

**Comment by ashwinvis** [comment]
Actually, I just realized activating the option for mermaid would use https://www.npmjs.com/package/markdown-it-textual-uml/ which also supports plantuml. so this would just work out of the box. You would probably need to install the latest versions from git to make it work until it is released.
