### ISSUE TITLE
macosx: only white page in browser

### ISSUE THREAD

**Issue by seebi** [instant-markdown/vim-instant-markdown#59]
after loading a markdown file, a new browser tab opens but only a white page is seen (with the following source):

```
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="/node_modules/docter/ghf_marked.css" />
  <script src="/socket.io/socket.io.js"></script>
  <script>
    var socket = io.connect('http://localhost:8090/');
    socket.on('connect', function () {
      socket.on('newContent', function(newHTML) {
        document.body.innerHTML = newHTML;
      });
      socket.on('die', function(newHTML) {
        window.open('', '_self', '');
        window.close();

        var firefoxWarning =
        "<h1>Oops!</h1>" +
        "<h3>Firefox doesn't allow windows to self-close.</h3>" +
        "<h3>If you want the preview window to close automatically like in other browsers, go to about:config and set dom.allow_scripts_to_close_windows to true.</h3>"
        document.body.innerHTML = firefoxWarning;
      });
    });
  </script>
</head>
<body>
</body>
</html>
```

**Comment by simonweil** [comment]
Doesn't work for me either, tried all the above tricks.

OS: MAC OSX Yosemite (10.10.2)
Browser: Firefox

**Comment by alexdunn** [comment]
@egel 's steps seem to have solved it for Ubuntu users, but not for Mac users.  I'm also having this problem.  Always nothing but a white page showing up in the browser.

**Comment by shenxs** [comment]
@suan  Thank you !! It works on ubuntu 14.04 LTS chrome

**Comment by xanderdunn** [comment]
shime/livedown worked for me on OSX without any configuration or difficulties.

**Comment by robbie-cao** [comment]
I have the issue browsing with Chrome, but Firefox works fine.
MacOS El Captain.

**Comment by tukoz** [comment]
@basvandenberg's comment:

    sudo gem install pygments.rb redcarpet
without the space beteen red carpet.
Works for Arch linux.

Also just in case it needs Javascript ON in the $BROWSER.
