### ISSUE TITLE
Problem with markdown compilation

### ISSUE THREAD

**Issue by egel** [instant-markdown/vim-instant-markdown#60]
I've noticed that many people have similar problem during compilation of markdown files. I also have it.
Usually users think that is wrong instalation of software (sometimes it is), but the problem is probably with used markdown compiler.

I spin around for a while trying to debug what can cause this bug and I found some interesting issues with compilation process.
1. Some word into header section can't be compile properly:
   
   ```
   ##  Użytkownik  (FAIL with "ż" sign)
   ```
   
   but below sample dump text compile properly.
   
   ```
   ## DasdfFAFfgsvsv żżżżż
   ```
2. Code snippets with given language formatting:
   
   Correct:
   
   ``````
   ```
   cd some sample code
   ```
   ``````
   
   Fail:
   
   ``````
   ```shell
   cd some sample code
   ```
   ``````

I'm not sure yet what is the main source of this issue, but I'm convinced that this bunch of problems is caused mainly by markdown compilator or "Github markdown flavor" styles.

Did you observe the same problem on your machines?

**Comment by t-0-m-1-3** [comment]
> I've noticed that many people have similar problem during compilation of markdown files. I also have it.
> Usually users think that is wrong instalation of software (sometimes it is), but the problem is probably with used markdown compiler.
> 
> I spin around for a while trying to debug what can cause this bug and I found some interesting issues with compilation process.
> 
>     1. Some word into header section can't be compile properly:
>        ```
>        ##  Użytkownik  (FAIL with "ż" sign)
>        ```
>        but below sample dump text compile properly.
>        ```
>        ## DasdfFAFfgsvsv żżżżż
>        ```
> 
>     2. Code snippets with given language formatting:
>        Correct:
>        ```
>        ```
>        cd some sample code
>        ```
>        ```
>        Fail:
>        ```
>        ```shell
>        cd some sample code
>        ```
>        ```
> 
> 
> I'm not sure yet what is the main source of this issue, but I'm convinced that this bunch of problems is caused mainly by markdown compilator or "Github markdown flavor" styles.
> 
> Did you observe the same problem on your machines?

try 
```bash
cd ~/place/to/go
```
