### ISSUE TITLE
opening multiple markdown files 

### ISSUE THREAD

**Issue by jhjlee** [instant-markdown/vim-instant-markdown#66]
I am not entirely sure whether this is an issue or whether this is supported at all, but here goes.

When I open up multiple markdown files, only the preview of the last markdown file will open. When this happens, the preview of the **previous** markdown file will be replaced with an **empty** window. 

I am just wondering whether the preview of multiple markdown files can be done (and also editing of multiple markdown files simultaneously), or only one markdown files can be edited/previewed at one time?
Thanks.

**Comment by yusiwen** [comment]
Same issue here (Ubuntu 15.04, vim 7.3, node.js 0.10.3).

It seems that only one vim instance should be running Instant_markdown, others can't work.

**Comment by yusiwen** [comment]
Furthermore, I'v found that when I opened multiple .md files in one vim instance by :tabe FILENAME command, it still can't show correctly preview in browser.

**Comment by wamoyo** [comment]
+1

**Comment by wamoyo** [comment]
I have the same issue.
