### ISSUE TITLE
Why is the entire plugin in after/ftplugin/?

### ISSUE THREAD

**Issue by dbarnett** [instant-markdown/vim-instant-markdown#76]
Normally `after/` is only used to override configuration from other plugin files. Doing this in a plugin unless there's a good reason can cause problems for users. Is there a reason the entire plugin lives in after/ftplugin/? If so, please update the plugin to add a comment somewhere explaining why that's necessary.

**Comment by ashwinvis** [comment]
Because it is only useful for markdown filetype.

**Comment by dbarnett** [comment]
I think you're answering why it's under ftplugin/. I'm asking why there's an "after" parent directory over that. Did you run into some problem using `ftplugin/` that you needed to work around by moving it under `after/ftplugin/`?

Normally `after/` exists only for a user to override something a plugin is doing that they don't like, and if a plugin puts files in after then users can't add their own overrides (see notes at https://google.github.io/styleguide/vimscriptfull.xml#Structure).

**Comment by ashwinvis** [comment]
Fair point. Thanks for the remark.
