### ISSUE TITLE
Markdown code does not work correctly

### ISSUE THREAD

**Issue by QMonkey** [instant-markdown/vim-instant-markdown#88]
Example code is below (Please remove '@'). It doesn't work correctly in vim-instant-markdown, but work correctly in github issue.

<pre>
# [POST] /abc/cde/efg

- TestA
- TestB
- TestC

<@!-- -->
    Test test test
    test test setst
</pre>

**Comment by schoetbi** [comment]
I noticed the same. As soon as you have a list directly followed by a code block the code block is rendered as normal text. 

Example:

This does not work
```
- one
- two
- three

    struct MyStruct {
        
    }
```
This works

```
- one
- two
- three

<br>

    struct MyStruct {
        
    }
```
